import Head from 'next/head'
import ConectarBD from '@/lib/dbConect'
import Movie from '../models/Movie'
import Table from '@/components/Table'
import Layout from '@/layouts/Layout'
import Dashboard from './dashboard/page'
import { PrimeReactProvider } from 'primereact/api';
import { useEffect } from 'react'
import 'primereact/resources/themes/bootstrap4-light-blue/theme.css';

export default function Home({movies}) {
  return (
    <PrimeReactProvider>
      <Head>
        <title>Pelisplus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Layout>
            <main>
              <Dashboard movies={movies} />
            </main>
          </Layout> 
    </PrimeReactProvider>
  )
}

export async function getServerSideProps() {
  try {
    await ConectarBD();
    const res = await Movie.find({})
    const movies = res.map((doc)=>{
      const movie = doc.toObject()
      movie._id = `${movie._id}`
      return movie
    })
    return {props: {movies}}
  } catch (error) {
    console.error(error);
    return {
      props: {
        error: error.message || 'Error inesperado',
      },
    };
  }
}
