import Head from 'next/head'
import ConectarBD from '@/lib/dbConect'
import Movie from '../models/Movie'
import Link from 'next/link'
import Style from '../styles/index.module.scss'

export default function Home({movies}) {
  return (
    <>
      <Head>
        <title>Pelispulus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className={Style.title}>Peliculas Disponibles</h2>
        <Link className={Style.addMovie} href='/New'>Añadir pelicula</Link>
        <div className={Style.ContainerGrid}>
        {
          movies.map(({_id, title, description, image})=>(
            <div className={Style.CardMovie} key={_id}>
                <div>
                  <img className={Style.ImgMovie} src={`${image}`} width={'150'} height={'150'} alt={'Picture movie'}/>
                </div>
                <div className={Style.CardBody}>
                  <h5 className={Style.titleMovie}>{title}</h5>
                  <p className={Style.descriptionMovie}>{description}</p>
                </div>
                <Link href={`/${_id}`} className={Style.btnInfoMovie}>Mas info...</Link>
            </div>
          ))
        }
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    await ConectarBD();
    const res = await Movie.find({})
    const movies = res.map((doc)=>{
      const movie = doc.toObject()
      movie._id = `${movie._id}`
      return movie
    })
    return {props: {movies}}
  } catch (error) {
    console.log(error)
  }
}
